### ISSUE TITLE
Random lexing error; native fallback fails

### ISSUE THREAD

**Issue by DrTom** [cucumber-attic/gherkin2#245]
We get (more or less) random lexing errors like the following: 

```
features/guest_user.feature: Lexing error on line 4: ''
```

This is on C/MRI Ruby 1.9.3-p392, gherkin 2.11.6

I tried to fall back to the ruby lexer as suggested (e.g. in https://github.com/cucumber/gherkin/issues/182), along the following: 

```
Gherkin::I18n.class_eval do
  alias_method :orig_lexer, :lexer
    def lexer(listener, force_ruby=false)
    orig_lexer(listener,true)
  end
end
```

Then we will get a 'no lexer found exception':

```
No lexer was found for en (cannot load such file -- gherkin/lexer/en)
```

I am not concerned about the performance. Is there a way to make  the native ruby lexer work?

**Comment by caseyding** [comment]
@jcwilk Could you tell me how I can install ragel on windows 7?

**Comment by jcwilk** [comment]
@caseyding I tend to avoid using ruby in windows whenever possible (I run a linux VM in windows) and my issue was in ubuntu, so I can't really help there or say whether it might be the same issue as I don't want to just make a guess and lead you down the wrong road.

It sounds like if you have cucumber/gherkin on recent versions the issue probably isn't still present by now since this was two years ago?

If you suspect it is, you might want to tag some of the others who actually know what they're doing here :P But I suspect it's something else unless you absolutely have to use an old version (again, mostly guessing)

**Comment by aslakhellesoy** [comment]
Gherkin2 will soon be replaced by [Gherkin3](https://github.com/cucumber/gherkin3) and we don't plan to make any more Gherkin2 releases.

**Comment by marciok** [comment]
I'm still facing this issue with cucumber 2.0.2, The scenario is falling randomly.

Is there a way to use Gherkin3 with cucumber 2.0.2 ?

**Comment by brasmusson** [comment]
@marciok If you are willing to use not yet released versions, you can follow the instructions in: https://github.com/cucumber/gherkin/issues/257#issuecomment-136161492.

**Comment by marciok** [comment]
Awesome @brasmusson, thanks!

**Comment by brasmusson** [comment]
@marciok Cucumber 2.1 (using Gherkin3) was just [released](https://groups.google.com/forum/#!topic/cukes/hkwfW8NZoyA) so there is no need for using gems from github anymore.

**Comment by marciok** [comment]
@brasmusson Thanks again! 🎉🎊
